### ISSUE TITLE
Problem with 4k screen on windows 10 and maybe scaling

### ISSUE THREAD

**Issue by R0TEAM** [midspace/SEToolbox#100]
Hi,

on my 4k screen SEToolBox dont start after the first run, as it writes IMHO the last window coords in the registry, and the result is values like :
WindowHeight    828.41958041958

if i correct this to non floating point values - like 828 , then it starts and work flawless.
(till the next start ...)

Regards

**Comment by midspace** [comment]
Microsoft documentation specifically indicates that the Height property is a double (floating point).
It should be able to handle 828.41958041958
https://msdn.microsoft.com/en-us/library/system.windows.frameworkelement.height(v=vs.110).aspx

The documentation doesn't indicate that scaling is a factor, as it is fixed:
`This value is interpreted as a device-independent unit (1/96th inch) measurement. `

What it might be, is regionalization. A culture specific conversion of the value after reading it from the registry.
So it's try to set the Window Height to 82841958041958

So the confirmation is, what language is your desktop running as?

**Comment by R0TEAM** [comment]
German

and yes .. the error window say "value xxxxxxxxxx is out of range" or similar ... and i have thinked, "mhh ... i see an digit after 3 numbers in the registry .. maybe it is not displayed in the error window ..? "

**Comment by midspace** [comment]
The latest release should fix this issue:
https://github.com/midspace/SEToolbox/releases/latest

**Comment by R0TEAM** [comment]
Jup - Fixed __ THANKS __
