### ISSUE TITLE
triggers Microsft security screen

### ISSUE THREAD

**Issue by Anora** [midspace/SEToolbox#101]
triggers Microsft security screen did not do this whit previous install's

**Comment by midspace** [comment]
The Windows Defender SmartScreen is designed to protect you from "unrecognised" applications.
Every new build of an application is essentially new, so unfortunately the new version of SEToolbox has zero reputation with Microsoft's Windows Defender database.

If you have set you Defender to Block all unrecognised applications it won't run SEToolbox until many other people have downloaded and run it also with Windows Defender in the background.

The alternative is to change your Windows Defender SmartScreen settings to "Warn" you of an unrecognised application, however it is then up to you to allow it or not.
I certainly **do not** recommend turning Defender SmartScreen off.

There are some steps outlined here on how to access Defender SmartScreen settings,
http://winaero.com/blog/disable-smartscreen-windows-10-creators-update/

**Comment by TerrorBite** [comment]
I also experienced Defender SmartScreen when running the latest (released 24h ago).

Have you considered signing your executables?

**Comment by midspace** [comment]
I have considered signing, but it isn't a guarantee that it won't trigger Defender unless I buy a certificate from more expensive provider. Additionally, the process of vetting an individual is not detailed. Vetting is usually done for a company. Typically you would have a business registration, and other documentation to prove the business exists.

**Comment by nugunsknight** [comment]
Just turn smart screen off?

**Comment by midspace** [comment]
I will not recommend turning it off.

I have mine set as below, to Warn in Windows 10.
![smartscreen](https://user-images.githubusercontent.com/6026063/29866439-bb0f2a4c-8dbb-11e7-8651-ef03af79b843.png)
