### ISSUE TITLE
Suggestion: Player Hydrogen

### ISSUE THREAD

**Issue by VasVadum** [midspace/SEToolbox#103]
You seem to have forgotten to add Hydrogen editing for players :P I can't set my hydrogen back up when I ran completely out and got stuck in a hole thanks to glitches.  Saved and exited, opened this toolbox up and can't give myself new hydrogen.  I can't spawn a can either cause it just crashes when I click "add".

**Comment by midspace** [comment]
I haven't seen any issue with crashing when adding items.
Can you provide me a copy of your event log?

I do have one issue adding the hydrogen bottle though. They are empty. :(
I'll have a look into all those issues.

**Comment by VasVadum** [comment]
My map had over 100 mods in it, so maybe it was a crash caused by that?
I wasn't talking about player inventory though, player characters use hydrogen for propulsion, so we need a way to refill that from the SEToolbox now, like you have with health and battery.

**Comment by midspace** [comment]
The new release has the changes for hydrogen levels, and fixes to oxygen levels and bottles.
https://github.com/midspace/SEToolbox/releases/latest

**Comment by VasVadum** [comment]
Now if only I could update without having to DL latest releases each time :P I like in app updates usually.
