### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by Christian-Thiem** [midspace/SEToolbox#105]
Application crashes on starup with: 

```
"An Error has been detected in the application that caused the application to shut down: "124133333333333" is a invalid value for this preference.
Valid Values are reaching from "Int32.MinValue" to "Int32.MaxValue"
Please see application event log for more detailes
```

**Comment by midspace** [comment]
please provide a copy of the event log.
To find the the event log, follows the steps described here:
https://github.com/midspace/SEToolbox/wiki/Reporting-bugs

**Comment by Christian-Thiem** [comment]
> 2017-09-03 15:58:40,616 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
> Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
> CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" /B /B
> CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
> SEBinPath: C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64
> SEBinVersion: 1.183.200
> ProcessorCount: 8
> OSVersion: Microsoft Windows NT 6.2.9200.0
> Version: 4.0.30319.42000
> Is64BitOperatingSystem: True
> IntPtr.Size: 8
> IsAdmin: False
> CurrentUICulture: de-DE
> CurrentCulture: 
> 
> Files:
> 2017-09-03T15:56:40.2084063+02:00	21,554,224		HavokWrapper.dll
> 2017-06-02T07:49:12.0000000+02:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
> 2015-11-23T08:03:56.0000000+01:00	200,704	0.86.5.0	ICSharpCode.SharpZipLib.dll
> 2017-09-03T15:56:40.8555120+02:00	34,864	1.0.0.0	InfinarioSDK.dll
> 2017-03-08T17:26:22.0000000+01:00	276,480	2.0.8.0	log4net.dll
> 2016-01-27T16:41:07.3993784+01:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
> 2016-01-27T16:41:08.8681462+01:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
> 2017-09-03T15:56:41.7693303+02:00	68,144	1.0.0.0	Sandbox.Common.dll
> 2017-09-03T15:56:41.9989929+02:00	6,706,736	1.0.0.0	Sandbox.Game.dll
> 2017-09-03T15:56:41.2398572+02:00	364,592	1.0.0.0	Sandbox.Graphics.dll
> 2017-08-25T07:33:06.0000000+02:00	1,304,064	01.183.100.1	SEToolbox.exe
> 2017-06-02T07:49:12.0000000+02:00	745		SEToolbox.exe.config
> 2017-06-20T18:09:16.0000000+02:00	29,184	1.0.0.0	SEToolbox.ImageLibrary.dll
> 2017-08-25T07:33:04.0000000+02:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
> 2017-08-25T07:33:06.0000000+02:00	2,160,128		SEToolbox.pdb
> 2017-08-23T16:23:24.0000000+02:00	51,712	1.0.0.0	SEToolboxUpdate.exe
> 2017-09-03T15:56:42.1450852+02:00	269,872	3.1.0	SharpDX.dll
> 2017-09-03T15:56:42.3295102+02:00	413,744	1.0.0.0	SpaceEngineers.Game.dll
> 2017-09-03T15:56:42.3820848+02:00	55,856	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
> 2017-09-03T15:56:43.2925151+02:00	11,238,448	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
> 2017-09-03T15:56:42.4584925+02:00	683,568		SteamSDK.dll
> 2017-08-17T22:05:38.1372258+02:00	242,976	03.75.32.07	steam_api64.dll
> 2017-09-03T15:56:42.4439808+02:00	302,128	1.0.98.0	System.Data.SQLite.dll
> 2013-03-09T16:25:10.0000000+01:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
> 2017-09-03T15:56:42.5390365+02:00	22,576	1.0.0.0	VRage.Ansel.dll
> 2017-09-03T15:56:42.5280283+02:00	73,776	1.0.0.0	VRage.Audio.dll
> 2017-09-03T15:56:42.5825674+02:00	446,000	1.0.0.0	VRage.dll
> 2017-09-03T15:56:42.6901422+02:00	1,032,752	1.0.0.0	VRage.Game.dll
> 2017-09-03T15:56:42.9147415+02:00	3,369,008	1.0.0.0	VRage.Game.XmlSerializers.dll
> 2017-09-03T15:56:42.6461125+02:00	97,328	1.0.0.0	VRage.Input.dll
> 2017-09-03T15:56:42.7281710+02:00	668,208	1.0.0.0	VRage.Library.dll
> 2017-09-03T15:56:42.7992211+02:00	520,752	1.0.0.0	VRage.Math.dll
> 2017-09-03T15:56:42.8281805+02:00	78,384		VRage.Native.dll
> 2017-09-03T15:56:42.8401890+02:00	105,008	1.0.0.0	VRage.OpenVRWrapper.dll
> 2017-09-03T15:56:42.8822177+02:00	327,216	1.0.0.0	VRage.Render.dll
> 2017-09-03T15:56:42.9477653+02:00	915,504	1.0.0.0	VRage.Render11.dll
> 2015-06-29T00:00:10.0000000+02:00	71,168	2.3.2	WPFLocalizeExtension.dll
> 2016-05-04T23:32:16.0000000+02:00	27,648	1.2.2	XAMLMarkupExtensions.dll
> 
> System.ArgumentException: "124133333333333" ist kein gültiger Wert für diese Eigenschaft. Gültige Werte reichen von "Int32.MinValue" bis "Int32.MaxValue".
>    bei System.Windows.Window.ValidateLengthForHeightWidth(Double l)
>    bei System.Windows.Window.OnWidthChanged(Double width)
>    bei System.Windows.Window._OnWidthChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
>    bei System.Windows.PropertyChangedCallback.Invoke(DependencyObject d, DependencyPropertyChangedEventArgs e)
>    bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
>    bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
>    bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>    bei System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
>    bei System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
>    bei SEToolbox.CoreToolbox.<>c__DisplayClass1_0.<Load>b__2(Object sender, RoutedEventArgs e) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\CoreToolbox.cs:Zeile 208.
>    bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    bei System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
>    bei System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
>    bei MS.Internal.LoadedOrUnloadedOperation.DoWork()
>    bei System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
>    bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
>    bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
>    bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
>    bei System.Windows.Interop.HwndTarget.OnResize()
>    bei System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
>    bei System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>

**Comment by midspace** [comment]
I will have a permanent fix for this in the next release.

You can repair SEToolbox settings like the start up location on screen, or the stored location of Space Engineers can be reset when you start SEToolbox. This can be done by holding down the `SHIFT` key as you start up SEToolbox.
