### ISSUE TITLE
Pointing to the Wrong SpaceEngineers Application

### ISSUE THREAD

**Issue by InquiM** [midspace/SEToolbox#106]
when launching the the Toolbox it looks for SpaceEngineers instead of SpaceEngineersDedicated. if you select the Dedicated one it gives and error.
![capture](https://user-images.githubusercontent.com/31260444/29591135-1493f160-8795-11e7-9f41-01c08c9dccd1.PNG)
![capture2](https://user-images.githubusercontent.com/31260444/29591161-22045470-8795-11e7-9a51-e6eca9b521ec.PNG)

**Comment by midspace** [comment]
I've released an update to fix this issue.
https://github.com/midspace/SEToolbox/releases/latest

**Comment by InquiM** [comment]
Fixed indeed. many thanks
