### ISSUE TITLE
Select all blocks of one color

### ISSUE THREAD

**Issue by mannmitmaske** [midspace/SEToolbox#119]
is there a way to select all blocks with a specific color ? if no, please consider adding it

**Comment by midspace** [comment]
Sort the blocks by colour, then you can select them.

**Comment by Lukevos** [comment]
All u have to do is hover over the block color and get the color code. Then type that color code into the search function and press enter. It'll give you all of the blocks in that color.

**Comment by midspace** [comment]
I forgot that I put search by color code in.
Yes, you can filter by the color code, or part code.

There are no wild cards in the search, but it will search on all words broken up by spaces.
So you can search for "44 Window"
"44" may be part of a color code, and "Window" part of the block name.
