### ISSUE TITLE
Error with replacing

### ISSUE THREAD

**Issue by PotatoedTophat** [midspace/SEToolbox#120]
Whenever I attempt to replace a block using the replace function, it has this error:

TimeSpan overflowed because the duration is too long

Error popup;
![capture](https://user-images.githubusercontent.com/34852119/34348901-6d9ecf00-e9d3-11e7-995e-2bb3352d4e41.PNG)

**Comment by midspace** [comment]
Could you please provide a copy of the world where you have have this issue, and describe which ship, and which blocks you are trying to replace with?

**Comment by midspace** [comment]
Closing after no response for more than a month.
