### ISSUE TITLE
Inventory property grid has no scroll bar

### ISSUE THREAD

**Issue by dodexahedron** [midspace/SEToolbox#121]
The inventory editor does not have a vertical scroll bar, so it's pretty hard to use without resizing the panels.

**Comment by dodexahedron** [comment]
I see that it's using the default for scroller visibility (which is automatic) in the xaml, but the scroll bar still doesn't show up.
When forced visible (ie `VerticalScrollBarVisibility="Visible"`), the scroll bar is always disabled, even if scrolling should be necessary.

I played with the visual tree for a good two hours, trying to find a way to make that thing scroll like it should, but I'm convinced it's due to the template for the custom datagrid.

Perhaps this one might be easier as a ListView, since sorting is disallowed anyway (so really all the datagrid functionality is kinda being tossed out), and then plain old ItemTemplates can be used in the XAML?

**Comment by midspace** [comment]
Released in https://github.com/midspace/SEToolbox/releases/tag/v1.186.29.0
