### ISSUE TITLE
Game crashes after clicking on 3D Model button.

### ISSUE THREAD

**Issue by Tschicky** [midspace/SEToolbox#125]
as said in the title my clint crashes after pressing the **_3D model button under Import_**. There is for a short time a white window and after that I get a crash allert cause of a problem the programm doesnt work fine. and the application´ll close.

**Comment by midspace** [comment]
Hi Tschicky.
Could you please provide a copy of the Event Log, as described here:
https://github.com/midspace/SEToolbox/wiki/Reporting-bugs

**Comment by midspace** [comment]
Closing after no response for more than a month.
