### ISSUE TITLE
Can't load maps due to major SE update yesterday

### ISSUE THREAD

**Issue by Lukevos** [midspace/SEToolbox#128]
The update yesterday for SE to the visuals, audio, and wheels broke the tool. Something to do with the new voxels.

I get this error --->
![image](https://user-images.githubusercontent.com/11171772/35767626-0232d73e-08be-11e8-9d79-f88d786fde94.png)

**Comment by TokMor** [comment]
I haven't done a huge amount of testing, but I've noticed that if I make a brand new world in the new patch the save opens fine, but if I open a world that was started on an old patch then I get the error noted above.

**Comment by Lukevos** [comment]
That's weird.

**Comment by midspace** [comment]
I can't tell what version of SE or SEToolbox you are running (the top of the image was cropped)
The Event Log will help me more.
Please see the following on retrieving the Event Log.
https://github.com/midspace/SEToolbox/wiki/Reporting-bugs

Please make sure you are using the latest SEToolbox https://github.com/midspace/SEToolbox/releases/latest

I am concerned though.
Your dialog says `Sandbox.Game, Version=0.1.6607.29602.`

The official Sandbox.Game.dll should be version `1.0.0.0`

If you have a not-quite-legit copy, then see if you can get a more recent version.

**Comment by Lukevos** [comment]
Are you talking about a more recent version of SE or the Toolbox?

**Comment by Lukevos** [comment]
I just reinstalled the Toolbox with the link you provided. It works now. Very odd.

**Comment by midspace** [comment]
the `MyVoxelMaterialDefinition` was moved in the game code between 1.185 and 1.186.
This is the major reason for the SEToolbox update.

If you don't have further problems I will close this issue.
