### ISSUE TITLE
Application crashes on using the 3D Model import

### ISSUE THREAD

**Issue by HBx90** [midspace/SEToolbox#130]
Everything works fine but the 3D model feature under the import menu. It opens the usual window but it is blank inside and the application stops working.
It happens everytime i try to use it.
I already tried to reinstall/update the application.
I get this application error log:
Name of the application that generated the error: SEToolbox.exe, version: 1.186.29.0, 
timestamp:  0x5a74e09b
Name of the module that generated the error: atiumd64.dll, version: 23.20.15002.11, 
timestamp: 0x5a287485
Exception code: 0xc0000005
Offset error: 0x00000000002fee98
ID process that generated the error: 0x1170
Start time of the application that generated the error: 0x01d3a631be84d125
Path to the application that generated the error: C:\Users\HB\Desktop\SEToolBox\SEToolbox.exe
Path to the module that generated the error: C:\Windows\system32\atiumd64.dll
ID report: 1d894f26-1225-11e8-9ef0-704d7b62ee12

(I manually translated the calls to english)

**Comment by SchlauFuchs** [comment]
I seem to have memory overflow issues with the import function. The app claims all memory it can get - more than 12GB on my host, everything becomes unresponsive, probably paging, then the app dies.

Here is a ship model I try to import:
https://www.dropbox.com/s/kv758jyh61clfk5/Perry%20Rhodan%20-%20Korvette.3ds?dl=0

**Comment by midspace** [comment]
@HBx90 Can you please provide the 3d model file you are using, and a screen capture of the settings you are using.

@SchlauFuchs Can you please start a new issue for your problem.

**Comment by SchlauFuchs** [comment]
I think you can ignore me this time - after I received last weeks SE update the problem disappeared.

**Comment by midspace** [comment]
Closing after no response for more than a month.
