### ISSUE TITLE
Feature Request-Small/ Large

### ISSUE THREAD

**Issue by CTH999** [midspace/SEToolbox#135]
So, here's my idea: An ability to turn large-grids into small grids, and, visa-versa. I don't know if it's feasible, or even possible, but, it's an idea!

**Comment by midspace** [comment]
This features was added into my Mod here [Midspace's Admin helper commands](https://steamcommunity.com/sharedfiles/filedetails/?id=316190120)
Use the chat command `/scaledown` and `/scaleup` in game. More details on some of chat commands are here: [chat commands wiki](https://github.com/midspace/Space-Engineers-Admin-script-mod/wiki/Ship-management-Admin-Commands)

At this stage I don't intend to replicate this functionality in SEToolbox as it is better to use this sort of functionality directly in game.
