### ISSUE TITLE
Translations, duplicates. (reccomendation)

### ISSUE THREAD

**Issue by BaconFist** [midspace/SEToolbox#139]
I did some Translations and there are many many many many duplicates. I mean most of the translations are doubled or trippled.

For example:
DialogExportHtmlFileTitle, DialogExportTextFileTitle,DialogExportXmlFileTitle .. all with the same Text.
Same with LargeShip/SmallShip and a bunch more.

**Comment by midspace** [comment]
It's standard practice to create control labels for each individual control.
Even if the text appears as a duplicate in one language, it may be subtly different in another language based on the context of where the control is used.

Additionally, if one control is later changed and the text changed as a result, it significantly reduces maintenance. Typically what happens is, the developer will load the text and change it for that control to suit the new purpose, possibly not realizing that it may be used by more than control. Then someone has to look for every control or code using the same display text and duplicate them before renaming the one they want.
Making sure there is one text resource for each control simplifies the development and ongoing maintenance of the application.

**Comment by midspace** [comment]
One of my concerns is what to call this in Deutsche.
As it has two names.
The long title. "Space Engineers Toolbox"
The short title. "SEToolbox"

Now, I don't really know Deutsche, so I'm relying upon google translate, but it looks right.
The long title would be "Space Engineers Werkzeugkasten"
But that doesn't work too well with "SEToolbox" with is English connotations, or "SEWerkzeugkasten" which looks like a mouth full to me.
Is there an alternative which sounds short and snappy?

**Comment by BaconFist** [comment]
ah I see. 

I would not translate the application  name. 
Stock with SEToolbox. there are thing that should not be translated.

you wouldn't translate "Space Engineers" to "Weltraum-Ingenieur" either.

**Comment by midspace** [comment]
Duplicates are acceptable, as they represent different controls. Closing.
