### ISSUE TITLE
Importing 3D Model

### ISSUE THREAD

**Issue by Tschicky** [midspace/SEToolbox#140]
first of all sr that I didnt responde
I have still the same issue and here is my event log and the crashtext

https://drive.google.com/open?id=1Yj2cJtXN0Q4UCS8krf7ioJ-UBPh5FK02

ty

**Comment by midspace** [comment]
Please download the latest version of SEToolbox, from here: https://github.com/midspace/SEToolbox/releases/latest

There were some breaking changes when KeenSWH released version 1.186.x of Space Engineers in February.
You appear to be still running a version from last year.

**Comment by Tschicky** [comment]
ty very much
I though it was the actual because there is a window when I started the app that says that I need to upgrade so I though if I press ok it ll update automatic

**Comment by CTH999** [comment]
It doesn't auto-update (sadly)

For that idea, see [This Issue](https://github.com/midspace/SEToolbox/issues/142l)

And, it's good it got fixed!

**Comment by Tschicky** [comment]
yep ty very much


2018-08-08 16:29 GMT+02:00 CTH999 <notifications@github.com>:
