### ISSUE TITLE
Run SEtoolBox on machine with only dedicated server installed

### ISSUE THREAD

**Issue by paranoidsystems** [midspace/SEToolbox#148]
SEToolbox 01.187.204 Release 1

So more a request than an issue. As a server Admin SEtoolbox is very useful and I am greatful for all teh work that goes into it 👍  now there is separate Steam application ID for installing just the SE Dedicated Server (APP ID 298740) this means you don't have to pull the entire game. Is it possible to have SEtoolbox support this type of install. I don't really want to installing Full fat SE on my server along side the Dedicated server. Currently I have to pull the saves off my server to my local machine to, do what I need, then reload it back onto the server. I don't know what SEtoolbox pulls from the game exe (or if those elements are in the dedicated server exe) so maybe this is not possible.

**Comment by midspace** [comment]
SEToolbox currently supports installation onto a computer that only has the Dedicated Server installation.
That is Steam AppId [298740](https://steamdb.info/app/298740/)
