### ISSUE TITLE
Memory Management/Runaway

### ISSUE THREAD

**Issue by necrogami** [midspace/SEToolbox#15]
So loading in large models I've experienced quite a bit of memory runaway till the system runs out of memory and the client crashes.

Is there a way to do some kind of management to prevent 100% memory usage and still load in large models?

**Comment by midspace** [comment]
Comment from Codeplex:

REPORTED ON: Sep 28, 2015 at 4:20 AM
REPORTED BY: Tableuraz
> Everytime one tries to import a model and create a ship with it, the memory used to register the model is never freed or released, meaning that the program's memory usage will get bigger and bigger as models get imported.
> The easier workaround would be to save the current scene inside a temporary file once the model has been converted, and delete the model from the RAM as it's not usefull anymore once it has been converted and put inside a file.

**Comment by midspace** [comment]
If there are specific areas you know that are using lots of memory I can try to target those.
Unfortunately the 3D voxel conversion does use a significant amount of memory which I have improved in the past, but it is by its very nature very memory hungry.


Memory handling in .Net is very different from common applications.
Objects are freed up automatically at intervals by the operating system by a process call Garbage Collection.
I cannot forcefully free up the memory in SEToolbox. I can add in some additional commands to speed up the process but this goes against all recommendations.

I added command to help with garbage collection in https://github.com/midspace/SEToolbox/commit/f0f10edd73b6ed853084c33321e97098f5199ef3 which should have helped.

**Comment by dodexahedron** [comment]
I think the GC.Collect call there may be pretty excessive. I don't imagine this has been revisited since Keen did some house cleaning?

Watching the profiler, while loading a world, you see just a solid line of GC invocations, which is really abnormal for any program and very expensive. World loads would probably be a lot faster in SEToolbox without it, or with a more conservative approach.
