### ISSUE TITLE
PixelShaderCompile Error MSB4062

### ISSUE THREAD

**Issue by williamhmic** [midspace/SEToolbox#153]
I have an issue. 
Line 98,5, .../Main/SEToolbox/SEToolbox.Image.Shaders/SEToolbox.ImageShaders.csproj
It says:
 error MSB406 2: The "ShaderBuildTask.PixelShaderCompile" task could not be loaded from the a
ssembly ShaderBuildTask, Version=1.0.3072.18169, Culture=neutral, PublicKeyToke
n=44e467d1687af125. Could not load file or assembly 'ShaderBuildTask, Version=1
.0.3072.18169, Culture=neutral, PublicKeyToken=44e467d1687af125' or one of its
dependencies. The system cannot find the file specified. Confirm that the <Usin
gTask> declaration is correct, that the assembly and all its dependencies are a
vailable, and that the task contains a public class that implements Microsoft.B
uild.Framework.ITask.

**Comment by williamhmic** [comment]
[msbuild.log](https://github.com/midspace/SEToolbox/files/2798980/msbuild.log)
@midspace

**Comment by midspace** [comment]
If you followed the developer guidelines, you should have installed the "Shader Effects BuildTask"
https://github.com/midspace/SEToolbox/wiki/Working-with-and-developing-SEToolbox
