### ISSUE TITLE
Crash on launch or open

### ISSUE THREAD

**Issue by ouroborus** [midspace/SEToolbox#166]
**SEToolbox Version:** 1.189.33 release 1
**SE Version:** 1.190.1

### SEToolbox crashed
At first it was clicking the "open" button, right after the open dialog dialog shows but before it could render content. It would hang and any mouse event would trigger the crash.

Then it degraded to crashing when trying to launch the app.

These claim to be out of memory errors but, given I have 32GB installed with only half in use, that doesn't seem possible.

### Steps to Reproduce
Launch app, click "open".
Or: Just launch app.

### SEToolbox Event Log

https://gist.github.com/ouroborus/2475c17857bb68a89dba5d3f90774784

**Comment by ouroborus** [comment]
It did do a synchronization with the SE data the first time it was launched.

**Comment by midspace** [comment]
Looking through the following articles, it appears to be rather difficult to solve issue on some hardware.

https://weblog.west-wind.com/posts/2016/dec/15/wpf-rendering-ducechannel-crashes-due-to-image-loading

https://social.msdn.microsoft.com/Forums/vstudio/en-US/8a494e51-8551-4f1d-9df6-5374b9de78e6/mediacompositionducechannelsyncflush-exception-in-win-12-terminal-server?forum=wpf

Microsoft write the following.

> It looks like it's something in the image that's causing WPF failing right at the render stage. which points at a render failure.

> We are not sure exactly what the issue is, but it's clear that WPF is having problems rendering the image file. May be there's something in the image parser that happens to have a problem on some video hardware.

> Unfortunately, there is no special solution for your issue. You need to do the first is you should check for are resource related issues and make sure you have the latest video drivers. 

If it is as random and specific to your hardware as you describe, then unfortunately I will have the same problems trying to locate or fix it. If truly is the native code, then there is nothing I can to do to help.

**Comment by ouroborus** [comment]
Alright, I'll see what I can do with regards to updating my drivers and rebooting. I don't reboot particularly often and this sort of thing doesn't seem to be effecting anything else. It may be a while before I get to it but I'll be sure to follow up once I do.

**Comment by ouroborus** [comment]
So, a pending Windows update made me think of this. I haven't done that yet and haven't rebooted since I started this issue but I launched SE Toolbox on a lark. Now it seems to run just fine.
