### ISSUE TITLE
SEToolBox Unable to launch - Locate application issue

### ISSUE THREAD

**Issue by Infinity-Bagel** [midspace/SEToolbox#167]
**SEToolbox Version:** 1.01.183.300.1
**SE Version:** 1.183.0

### SEToolbox failed to launch
What were you doing with SEToolbox when it happened?
While launching after I installed, the program prompted that "The Space Engineers application could not be located. Please specify the location of the Space Engineers Application file." The issue is that in the window it is prompting me in, it has the correct file path. I have not changed where the application file is located, so I am not sure why this error is occurring.

### Steps to Reproduce
1. How did this issue get triggered?
By running the application.
2. Write all of the steps here.
- Install application
- Run application, but cannot continue because of this issue.
![SEToolBoxCapture](https://user-images.githubusercontent.com/48464025/58509471-d954e900-8153-11e9-9009-80d9b686f03c.png)

**Comment by midspace** [comment]
Please ensure you have installed the latest version of SEToolbox installed. Visit [latest release](https://github.com/midspace/SEToolbox/releases/latest) to verify.

**Comment by midspace** [comment]
There has been a new update to address a number of issues in the previous release.
Please download the [latest release](https://github.com/midspace/SEToolbox/releases/latest).
