### ISSUE TITLE
Crash on saved game load.

### ISSUE THREAD

**Issue by Apollon-Theos** [midspace/SEToolbox#174]
- [x] Ensure you have installed the latest version of SEToolbox installed. Visit [latest release](https://github.com/midspace/SEToolbox/releases/latest) to verify.
- [x] Ensure that the issue is reproducible for testing. You may be requested to provide a link to a test world if we cannot reproduce it with your information.
- [x] Retrieve the Event Log from when SEToolbox crashed. Read the following [instructions](https://github.com/midspace/SEToolbox/wiki/Reporting-bugs) on retrieving the event log.

**SEToolbox Version:** 1.191.20.1
**SE Version:** 1.191.023

### SEToolbox crashed
What were you doing with SEToolbox when it happened?
![SEToolBox-error](https://user-images.githubusercontent.com/46534073/59382528-97888d00-8d66-11e9-9533-02bd52ea20f4.jpg)

### Steps to Reproduce
1. How did this issue get triggered?
Game based on Template from Steam's Workshop, with name "Learning to Survive"
2. Write all of the steps here.
Load a saved game, in SE all work, no problem in game, no problem by save.

### SEToolbox Event Log
Where I can find SEToolBox-Log ? In folder with SEToolBox not exist folder "Logs".
```
Paste your event log here.
```

**Comment by Apollon-Theos** [comment]
No event from SEToolBox in  EventViewer:
![SEToolBox-error-2](https://user-images.githubusercontent.com/46534073/59383004-bcc9cb00-8d67-11e9-97bc-d3744b31c0b8.jpg)

**Comment by Apollon-Theos** [comment]
List of installed MODS for this game:
![SEToolBox-error-3](https://user-images.githubusercontent.com/46534073/59383363-6d37cf00-8d68-11e9-8ef6-67262d8599d2.jpg)

**Comment by midspace** [comment]
Please download the [latest release](https://github.com/midspace/SEToolbox/releases/latest) for a fix to this issue.

**Comment by Apollon-Theos** [comment]
After update SEToolBox to version 1.191.20.2, all is work. Slow, but work. Very slow.
My Windows is Server 2012 R2.

**Comment by midspace** [comment]
Keen have added larger asteroids into the game, which appear to create performance issues when loading their details. Unfortunately the code that loads the asteroids is theirs, and it's out of my control.
