### ISSUE TITLE
The same Invalid Location Specified problem

### ISSUE THREAD

**Issue by hody108** [midspace/SEToolbox#185]
Hello, i have a problem with SEToolbox. It doesnt want to find SpaceEngineers.exe.
Can you fix please?

![Výstřižek](https://user-images.githubusercontent.com/56207541/66261391-ab03ac00-e7cc-11e9-9314-06af3d8e5ab3.PNG)

**Comment by midspace** [comment]
Duplicate of #180

**Comment by Rambo99** [comment]
Not fixed yet?

**Comment by hody108** [comment]
No it is not.

po 28. 10. 2019 v 10:56 odesílatel Andrey <notifications@github.com> napsal:
