### ISSUE TITLE
SETB not launching 

### ISSUE THREAD

**Issue by TB4T3M4N** [midspace/SEToolbox#188]
installed the latest version of SE Toolbox and it wont even launch

https://i.imgur.com/rfDPhhw.png

**Comment by lordadminchicken** [comment]
Midspace stopped working on this project last year. He put it right in the README at the bottom.

> ### Maintainence only
> I [midspace](https://github.com/midspace) have stopped working on Space Engineers related stuff.
> I will only be fixing issues that cause SEToolbox to crash. I won't be adding or enhancing any further features.
> There is a lengthy post [here](https://forum.keenswh.com/threads/7402115/) on the Keen forums about this decision.
> I'm open to other developers taking over, or at least contributing further to SEToolbox.

I have found this fork works: [https://github.com/mmusu3/SEToolbox](https://github.com/mmusu3/SEToolbox).
