### ISSUE TITLE
Stuck on "Locate Application" screen even though executable is selected

### ISSUE THREAD

**Issue by Nicistarful** [midspace/SEToolbox#189]
- [x] Ensure you have installed the latest version of SEToolbox installed. Visit [latest release](https://github.com/midspace/SEToolbox/releases/latest) to verify.
- [x] Ensure that the issue is reproducible for testing. You may be requested to provide a link to a test world if we cannot reproduce it with your information.
- [x] Retrieve the Event Log from when SEToolbox crashed. Read the following [instructions](https://github.com/midspace/SEToolbox/wiki/Reporting-bugs) on retrieving the event log.

**SEToolbox Version:** 01.191.20 Release 2
**SE Version:** 1.196

### Steps to Reproduce
1. Install SEToolbox
2. Locate application

### SEToolbox Event Log
```
No event log generated
```

![Screenshot 2020-09-30 194113](https://user-images.githubusercontent.com/50967431/94720560-edff4d80-0354-11eb-803b-044d61c09798.jpg)

**Comment by midspace** [comment]
As of 2019-08-23, this application is no longer kept up to date, and does not work.
It's in giant bold text on the main page.
https://github.com/midspace/SEToolbox

There is a fork here, which is rumoured to work. 
https://github.com/mmusu3/SEToolbox
