### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dublayl** [midspace/SEToolbox#192]
**SEToolbox Version:** 01.197.168.1
**SE Version:** 1.197.168

### SEToolbox crashed
What were you doing with SEToolbox when it happened?
Attempting to open it.

### Steps to Reproduce
1. How did this issue get triggered?
I double clicked the shortcut.
2. Write all of the steps here.
-double click shortcut to .exe
-click ok for update
-click yes on UAC prompt
-receive update error
**An error occuring whilst attempting to updating the base files.
You may attempt to run SEToolbox but you risk corrupting any Spaces Engineers world when you save.
It is recommended you close the application now, then download and install the latest version of SEToolbox as soon as possible.

If with to continue and attempt to run SEToolbox as it is, then press Yes to continue.
-click yes
-receive Space Engineers Toolbox '1.197.168.1' Error
**An error has been detected in the application that has caused the application to shut down:
Could not load file or assembly
'SpaceEngineers.ObjectBuilders, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
Apologies for any inconvenience.
-copy and pasted file into new folder

### SEToolbox Event Log
no event log

**Comment by midspace** [comment]
This application is no longer maintained.
Please see the main page for any details.

**Comment by midspace** [comment]
Please see other Issues for possible alternate applications.
