### ISSUE TITLE
SEToolBox.exe Cant find SpaceEngineers.exe even though i showed it manually

### ISSUE THREAD

**Issue by DragonBlood121** [midspace/SEToolbox#193]
I have lost my ship and i am trying to use this to get it back but its not working, i have show it manually where "SpaceEngineers.exe" is but its not doing anything and nor it is saying its valid, it is not on the same drive and it is a valid location so i have no idea whats wrong

![Capture](https://user-images.githubusercontent.com/81784242/113366788-d878d980-931f-11eb-9573-7580fc87e702.PNG)

**Comment by midspace** [comment]
This application is no longer maintained.
Please see the main page for any details.

**Comment by midspace** [comment]
Please see other Issues for possible alternate applications.
