### ISSUE TITLE
Crash repairing save

### ISSUE THREAD

**Issue by Herrumblo** [midspace/SEToolbox#194]
- [x] Ensure you have installed the latest version of SEToolbox installed. Visit [latest release](https://github.com/midspace/SEToolbox/releases/latest) to verify.
- [x] Ensure that the issue is reproducible for testing. You may be requested to provide a link to a test world if we cannot reproduce it with your information.
- [x] Retrieve the Event Log from when SEToolbox crashed. Read the following [instructions](https://github.com/midspace/SEToolbox/wiki/Reporting-bugs) on retrieving the event log.

**SEToolbox Version:** 1.198.24.1
**SE Version:** 198.031

### SEToolbox crashed
Repairing a save. "Object reference not set to an instance of an object"

### Steps to Reproduce
1. How did this issue get triggered?
Trying to repair a save where i cannot weld projected blocks.
2. Write all of the steps here.
Build a projector, load  a blueprint, trying to weld, cant weld.

### SEToolbox Event Log
```
I dont know where logs are stored.
```

**Comment by midspace** [comment]
This application is no longer maintained.
Please see the main page for any details.

Please see other Issues for possible alternate applications.
