### ISSUE TITLE
[Invalid location specified] Space Engineers application could not be located

### ISSUE THREAD

**Issue by KidozyGAME** [midspace/SEToolbox#195]
**SEToolbox Version:** 1.x.xxx.xxx
SEToolbox-01.191.20.2

**SE Version:** 1.xxx.xxx
1.200.030
### SEToolbox crashed

What were you doing with SEToolbox when it happened?
Null
[Invalid location specified] despite it being the game installation directory 

### Steps to Reproduce
1. How did this issue get triggered?
Locating install directory to select SpaceEngineers.exe

2. Write all of the steps here.
install to D:\SteamLibrary\steamapps\common\

### SEToolbox Event Log
N/A
![bandicam 2022-02-28 19-15-26-774](https://user-images.githubusercontent.com/68248542/156080642-d77f4550-2ff0-4496-87ed-9142149634bc.jpg)
![bandicam 2022-02-28 19-15-29-961](https://user-images.githubusercontent.com/68248542/156080643-d556d81e-7f80-4175-bc9b-eeba2bda5561.jpg)
![bandicam 2022-02-28 19-15-52-983](https://user-images.githubusercontent.com/68248542/156080645-61120528-80c1-4b52-a9d7-b404becc6685.jpg)

Space Engineers application could not be located

Paste your event log here.
```

**Comment by midspace** [comment]
This application is no longer maintained.
Please see the main page for any details.

Please see other Issues for possible alternate applications.
https://github.com/mmusu3/SEToolbox/releases
