### ISSUE TITLE
1.123.4.1 Error

### ISSUE THREAD

**Issue by Maelfunction** [midspace/SEToolbox#48]
After install with MSi or ZIP when it goes to update to the latest SE files the following message is displayed, I wasn't able to locate the log referenced.

An error has been detected in the application that has caused the application to shut down

The type initializer for 'SEToolbox.Interop.SpaceEngineerCore' threw an exception

Please see the Application Event Log for more details.
Apologies for any inconvenience

**Comment by midspace** [comment]
Please read the following on locating the Event log
https://github.com/midspace/SEToolbox/wiki/Reporting-bugs

**Comment by Noah83** [comment]
2016-02-29 19:05:02,506 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 
CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
SEBinPath: C:\GameServer\space\steamapps\common\SpaceEngineersDedicatedServer\DedicatedServer64
SEBinVersion: 1.123.7
ProcessorCount: 8
OSVersion: Microsoft Windows NT 6.2.9200.0
Version: 4.0.30319.42000
Is64BitOperatingSystem: True
IntPtr.Size: 8
IsAdmin: True
CurrentUICulture: de-DE
CurrentCulture: de-DE

Files:
2016-01-11T18:42:58.0000000+01:00	498.176	2014.2.17.1	HelixToolkit.Wpf.dll
2016-01-11T18:42:58.0000000+01:00	200.704	0.86.0.518	ICSharpCode.SharpZipLib.dll
2016-01-11T18:42:58.0000000+01:00	301.056	1.2.13.0	log4net.dll
2016-02-27T16:57:54.7775628+01:00	12.800	1.0.0.0	MedievalEngineers.ObjectBuilders.dll
2016-02-27T16:57:54.3853126+01:00	971.776	1.0.0.0	MedievalEngineers.ObjectBuilders.XmlSerializers.dll
2016-02-27T16:57:54.4343355+01:00	82.432	1.0.0.0	Sandbox.Common.dll
2016-02-25T20:19:24.0000000+01:00	1.178.624	01.123.004.1	SEToolbox.exe
2016-01-12T17:41:58.0000000+01:00	747		SEToolbox.exe.config
2016-02-25T20:19:18.0000000+01:00	27.648	1.0.0.0	SEToolbox.ImageLibrary.dll
2016-02-25T20:19:18.0000000+01:00	7.680	1.0.0.0	SEToolbox.ImageShaders.dll
2016-02-25T20:19:24.0000000+01:00	2.326.016		SEToolbox.pdb
2016-02-25T20:19:18.0000000+01:00	51.712	1.0.0.0	SEToolboxUpdate.exe
2016-02-27T16:57:54.8757668+01:00	43.520	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
2016-02-27T16:57:54.6244324+01:00	10.308.608	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
2016-01-11T18:42:58.0000000+01:00	39.936	2.0.20525.0	System.Windows.Interactivity.dll
2016-02-27T16:57:54.7775628+01:00	623.616	1.0.0.0	VRage.dll
2016-02-27T16:57:54.8757668+01:00	576.512	1.0.0.0	VRage.Game.dll
2016-02-27T16:57:54.8757668+01:00	2.297.856	1.0.0.0	VRage.Game.XmlSerializers.dll
2016-02-27T16:57:54.8767689+01:00	621.568	1.0.0.0	VRage.Library.dll
2016-02-27T16:57:54.7775628+01:00	464.384	1.0.0.0	VRage.Math.dll
2016-01-11T18:42:58.0000000+01:00	64.512	2.2.0	WPFLocalizeExtension.dll
2016-01-11T18:42:58.0000000+01:00	26.624	1.1.6.3	XAMLMarkupExtensions.dll

System.IO.FileNotFoundException: Die Datei oder Assembly "Sandbox.Game, Version=0.1.5898.29306, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
Dateiname: "Sandbox.Game, Version=0.1.5898.29306, Culture=neutral, PublicKeyToken=null"
   bei SEToolbox.Interop.SpaceEngineersRepair.RepairSandBox(WorldResource world)
   bei SEToolbox.ViewModels.SelectWorldViewModel.RepairExecuted() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\ViewModels\SelectWorldViewModel.cs:Zeile 191.
   bei SEToolbox.Services.DelegateCommand.Execute() in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:Zeile 72.
   bei SEToolbox.Services.DelegateCommand.System.Windows.Input.ICommand.Execute(Object parameter) in d:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:Zeile 154.
   bei MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   bei System.Windows.Controls.Primitives.ButtonBase.OnClick()
   bei System.Windows.Controls.Button.OnClick()
   bei System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

WRN: Protokollierung der Assemblybindung ist AUS.
Sie können die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) auf 1 festlegen.
Hinweis: Die Protokollierung der Assemblybindungsfehler führt zu einer gewissen Leistungseinbuße.
Sie können dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.

**Comment by midspace** [comment]
Thank @Noah83 
It looks like we have two new dependencies in the SE files.
Sandbox.Game.dll
HavokWrapper.dll

I will look at fixing the application to copy those in in about 8 hours.

**Comment by midspace** [comment]
@Maelfunction Have you had had any further issues with the recent release of SEToolbox?
If not, I will close this issue.

**Comment by midspace** [comment]
No response for over a month. I am closing this issue.
