### ISSUE TITLE
Move Build output folder

### ISSUE THREAD

**Issue by midspace** [midspace/SEToolbox#5]
Need to move the build output folder of build.bat to outside of the root of the source repository so it isn't automatically included in the Git.

**Comment by Chicken-Nugget** [comment]
All build results are automatically excluded by .gitignore

**Comment by midspace** [comment]
It's not the build results, it the release build generated when running the built.bat, which puts it into a folder off the root.
But it looks like it's okay, since the folder is named "bin".
