### ISSUE TITLE
Can't update files if Space Engineers is installed on another drive

### ISSUE THREAD

**Issue by MakeLord** [midspace/SEToolbox#59]
I have Space Engineers installed on a SSD drive, while Steam is on HDD, SEToolbox wasn't able to update files. I had to copy-paste Space Engineers folder from SSD to HDD so I could run it.

Please, add a config to change Space Engineers install folder, or something, so I won't have to copy-paste SE folder to HDD after every SE update.

**Comment by midspace** [comment]
If you have moved your installation of Space Engineers, SEToolbox will detect that the old one is gone and prompt you for the new location.

If you wish to forcefully update the location, hold down `shift` when you start SEToolbox.

**Comment by MakeLord** [comment]
> If you wish to forcefully update the location, hold down shift when you start SEToolbox.

It gives me an update error, saying that if I continue, I will risk corrupting any save file.

**Comment by midspace** [comment]
This occurs because the update failed to find the right files.
I also had this issue yesterday when testing with Avast.
There is probably an issue there because of all the recent changes that Keen have made in dependencies.
Your best choice right now is to uninstall SEToolbox, make sure the install path has been removed, and then reinstall it.

**Comment by midspace** [comment]
And make sure you choose the correct folder, Bin or Bin64 for your operating system.

**Comment by MakeLord** [comment]
Now after the newes SE update, it can't update files.

**Comment by midspace** [comment]
If you are accessing a dedicated server running as a Service instance, you must run SEToolbox with UAC elevated privileges.
Right click on your SEToolbox shortcut, and choose "Run as Administrator".

**Comment by MakeLord** [comment]
Ok, now it's working. Thanks
