### ISSUE TITLE
Unable to open save file with Eikesters mod collection

### ISSUE THREAD

**Issue by Fingersniffer** [midspace/SEToolbox#65]
When I try and open my save I get a message that the file 324812882.sbm is corrupt, deleted it and re-downloaded it, still the same problem

Mod in question:
https://steamcommunity.com/sharedfiles/filedetails/?id=324812882

**Comment by midspace** [comment]
That link is a **Collection**.  It is not a **Mod**.
Only Mod's can be added to games, not Collections.

**Comment by midspace** [comment]
P.S. I have given this idea directly to Keen to try and add into the game as a real feature. It would be real nice.

**Comment by Fingersniffer** [comment]
Understood, thank you.
