### ISSUE TITLE
Cubes>Filter crashes

### ISSUE THREAD

**Issue by MikiyGames** [midspace/SEToolbox#66]
While recently working on some save file i noticed that when using the filter box in the cubes tab the application crashes with an error message of "Object reference not set to an instance of an object".

Here is a save file for reproduction:
https://www.dropbox.com/s/1v9ncx9c3gffly9/ToolBoxIssue.7z?dl=0

**Comment by midspace** [comment]
This has been fixed in the Latest Release.
https://github.com/midspace/SEToolbox/releases/latest
