### ISSUE TITLE
Planet center location changes depending if world files are writable.

### ISSUE THREAD

**Issue by croxis** [midspace/SEToolbox#72]
I'm editing the save files of a dedicated server installed as a windows service, so elevated privileges are needed to save the world. The coordinates of the "center" of the planet differ depending on write levels.

The reason for such concern is that I am attempting to use blender to visually set up the placement of the planets, then enter the coordinates into SEToolbox. I do not know if the position parameters are suppose to represent the position of the planet, or one of the corners. It would be nice to edit planet position based on the center of the planet.

**Comment by midspace** [comment]
The latest release should now fix this issue.
My apologies for taking so long to fix this.
