### ISSUE TITLE
request fix for "Space Engineers application could not be located."

### ISSUE THREAD

**Issue by jackik1410** [midspace/SEToolbox#74]

**Comment by midspace** [comment]
What version of Space Engineers are you using?

What version of SEToolbox are you using?

Have you tried the latest version of SEToolbox?
https://github.com/midspace/SEToolbox/releases/latest

**Comment by jackik1410** [comment]
i am using the latest version of both SEToolbox and SpaceEngineers ( Dev branch ), more importantly though [maybe] i have both programs on different drives.

**Comment by midspace** [comment]
You mistake my questions.
Which version number precisely do you have?

Could you describe the steps you have taken?

They should resemble those described in the instructions:
https://github.com/midspace/SEToolbox/wiki/Installation#running-space-engineers-toolbox-the-first-time

**Comment by kelso-jp** [comment]
Hello,
I've found the same problem as reported by jackik1410. I hope this is the information you requested:

SEToolbox version 01.138.005.3
Space Engineers current content BuildID: 1150724
dx9-32bit - compatibility branch for dx9 and 32 bit

I have had SEToolbox running correctly before. However that was before I switched my version of Space Engineers to the compatability branch.

Both Space Engineers and SEToolbox are installed in their default directories.

The precise problem is:
1) Space Engineers updated to latest version
2) SEToolbox updated to latest version
3) Run SEToolbox for the first time
4) Splash screen displayed
5) 'Locate Application' dialog box displayed: 'The Space Engineers application could not be located. Please specify the location of the Space Engineers Application file.'
6) The correct path to the application (.exe) file is held in the text box, but 'Invalid location specified' message is displayed
7) Navigating to the application file again and updating the path in the text box do not resolve the problem
8) Continue button greyed out, unable to start application

I've attached an image of the dialog box.
![setoolbox error](https://cloud.githubusercontent.com/assets/20992291/17625306/3e70de8c-60e3-11e6-93e2-f30df6aa44fe.png)

**Comment by midspace** [comment]
@kelso-jp 
The latest version of SEToolbox will not work with the Space engineers compatibility branch for dx9 and 32 bit.

The last released version for SEToolbox that will work with that branch is here:
https://github.com/midspace/SEToolbox/releases/tag/v1.126.003.1

**Comment by kelso-jp** [comment]
Superb, problem resolved.
Many thanks for your quick response and ongoing support of SEToolbox! :)

**Comment by midspace** [comment]
No futher details provided by jackik1410. Closing issue.

**Comment by SpaceKadet125** [comment]
this is a problem in the installer, its been present for several years. if your SE install isint int he basic path you have to change the location, but the installer wont find it. even if you restart it dosent locate it and shows an error. If you immeadatly goto brows a second time and select the same file as before it wont show the error but the continue button will remain greyed out.
