### ISSUE TITLE
[Bug] Gas Shales are generated in old chunks!

### ISSUE THREAD

**Issue by ExDomino** [midspace/SEToolbox#76]
Hello, in Ingeneer Toolbox, Gas Shales are retro-generated in old chunk even if "Retro Gen Ores" is set to false. What's the problem?

**Comment by midspace** [comment]
I'm sorry. I do not understand.
Are you are native English speaker? Is there a translation issue?

I will guess you are having trouble with the generating asteroid field?

Please, read the following document on the problem.
It is an old problem. I am working on it. I do not have enough time to work on the issue this year. I am very delayed in fixing it.

https://github.com/midspace/SEToolbox/wiki/New-Asteroid-file-format

**Comment by ExDomino** [comment]
You're not the creator of Engineer's Toolbox ?

**Comment by midspace** [comment]
I am the author and creator of the Space Engineers Toolbox.

**Comment by midspace** [comment]
I'm sorry, I really don't know what you are talking about.

"Gas Shales", "old chunks", "retro-generated" and "Retro Gen Ores" are not features or terms that appear or are used in the Space Engineers game, or the Space Engineers Toolbox.

The Space Enginners Toolbox, or SEToolbox for short is an editor for The Space Engineers game.
All this is described on the main page.

**Comment by midspace** [comment]
I've googled around for those terms, and it really appears you have come here by mistake.
"Engineer's Toolbox" is tool or mod for "Minecraft".
You your probably find it more useful following the links on their pages:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290262-1-6-4-engineers-toolbox-customizable-modular


These are the pages for "Space Engineers Toolbox", a tool for the game "Space Engineers".
You can read up more about Space Engineers from the following pages, and buy it via Steam.
http://www.spaceengineersgame.com/
http://store.steampowered.com/app/244850


I have never played Minecraft, so I really had no idea what you were talking about,
As I don't support Minecraft or Minecraft tools, and this question is not about SEToolbox I will be closing it.
Thank you for your understanding.

**Comment by ExDomino** [comment]
Yes, google sent me to the wrong github page. Sorry!
