### ISSUE TITLE
SE ToolBox Crashing - Field not found... 

### ISSUE THREAD

**Issue by MichaelLDX** [midspace/SEToolbox#80]
When trying to drag an item, such as a ship or a station, from one window of SE ToolBox to another, the one I'm dragging out of will crash with "Field not found: 'Sandbox.Common.ObjectBuilders.MyObjectBuilder_PistonBase.TopBlockId'."

This is the general information provided by Event Viewer.

> 2016-09-25 15:11:22,364 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled 
> Exception
> Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
> CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 
> CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
> SEBinPath: D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64
> SEBinVersion: 1.149.4
> ProcessorCount: 8
> OSVersion: Microsoft Windows NT 6.2.9200.0
> Version: 4.0.30319.42000
> Is64BitOperatingSystem: True
> IntPtr.Size: 8
> IsAdmin: False
> CurrentUICulture: 
> CurrentCulture: 
> 
> Files:
> 2016-09-19T12:57:41.3795004-07:00	24,787,384		HavokWrapper.dll
> 2016-01-11T16:42:58.0000000-08:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
> 2016-01-11T16:42:58.0000000-08:00	200,704	0.86.0.518	ICSharpCode.SharpZipLib.dll
> 2016-01-11T16:42:58.0000000-08:00	301,056	1.2.13.0	log4net.dll
> 2016-06-27T14:00:26.6301630-07:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
> 2016-06-27T14:00:27.6885533-07:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
> 2016-09-19T12:57:41.3779978-07:00	52,664	1.0.0.0	Sandbox.Common.dll
> 2016-09-19T12:57:43.7140684-07:00	5,791,672	1.0.0.0	Sandbox.Game.dll
> 2016-09-19T12:57:43.7140684-07:00	312,248	1.0.0.0	Sandbox.Graphics.dll
> 2016-08-27T10:49:42.0000000-07:00	1,204,224	01.144.000.0	SEToolbox.exe
> 2016-06-15T18:45:08.0000000-07:00	745		SEToolbox.exe.config
> 2016-08-24T22:12:40.0000000-07:00	27,136	1.0.0.0	SEToolbox.ImageLibrary.dll
> 2016-08-27T10:49:40.0000000-07:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
> 2016-08-27T10:49:42.0000000-07:00	2,043,392		SEToolbox.pdb
> 2016-08-27T10:47:26.0000000-07:00	51,200	1.0.0.0	SEToolboxUpdate.exe
> 2016-09-19T12:57:41.3779978-07:00	262,072	3.0.1	SharpDX.dll
> 2016-09-19T12:57:44.5600622-07:00	328,632	1.0.0.0	SpaceEngineers.Game.dll
> 2016-09-19T12:57:44.4711451-07:00	51,128	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
> 2016-09-19T12:57:41.3789998-07:00	10,587,576	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
> 2016-09-19T12:57:44.4711451-07:00	537,016		SteamSDK.dll
> 2016-06-27T14:01:24.7466218-07:00	105,152	02.19.34.93	steam_api.dll
> 2016-06-27T14:00:27.3910490-07:00	119,488	02.19.34.93	steam_api64.dll
> 2016-01-11T16:42:58.0000000-08:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
> 2016-09-19T12:57:42.1952845-07:00	654,264	1.0.0.0	VRage.dll
> 2016-09-19T12:57:42.1952845-07:00	728,504	1.0.0.0	VRage.Game.dll
> 2016-09-19T12:57:44.5600622-07:00	2,766,264	1.0.0.0	VRage.Game.XmlSerializers.dll
> 2016-09-19T12:57:44.5595643-07:00	94,136	1.0.0.0	VRage.Input.dll
> 2016-09-19T12:57:42.6830532-07:00	648,632	1.0.0.0	VRage.Library.dll
> 2016-09-19T12:57:41.3795004-07:00	506,808	1.0.0.0	VRage.Math.dll
> 2016-09-19T12:57:42.1947607-07:00	76,728		VRage.Native.dll
> 2016-09-19T12:57:41.3789998-07:00	103,352	1.0.0.0	VRage.OpenVRWrapper.dll
> 2016-09-19T12:57:44.5610867-07:00	523,192	1.0.0.0	VRage.Render.dll
> 2016-09-19T12:57:42.6830532-07:00	604,600	1.0.0.0	VRage.Render11.dll
> 2016-01-11T16:42:58.0000000-08:00	64,512	2.2.0	WPFLocalizeExtension.dll
> 2016-01-11T16:42:58.0000000-08:00	26,624	1.1.6.3	XAMLMarkupExtensions.dll
> 
> System.MissingFieldException: Field not found: 'Sandbox.Common.ObjectBuilders.MyObjectBuilder_PistonBase.TopBlockId'.
>    at SEToolbox.Models.ExplorerModel.MergeData(MyObjectBuilder_CubeGrid cubeGridObject, Dictionary`2& idReplacementTable)
>    at SEToolbox.Models.ExplorerModel.MergeData(IList`1 data) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\ExplorerModel.cs:line 716
>    at SEToolbox.ViewModels.ExplorerViewModel.SEToolbox.Services.IDropable.Drop(Object data, Int32 index) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\ViewModels\ExplorerViewModel.cs:line 1752
>    at SEToolbox.Services.ListBoxDropBehavior.AssociatedObject_Drop(Object sender, DragEventArgs e) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\ListBoxDropBehavior.cs:line 107
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.OleDropTarget.RaiseDragEvent(RoutedEvent dragEvent, Int32 dragDropKeyStates, Int32& effects, DependencyObject target, Point targetPoint)
>    at System.Windows.OleDropTarget.MS.Win32.UnsafeNativeMethods.IOleDropTarget.OleDrop(Object data, Int32 dragDropKeyStates, Int64 point, Int32& effects)
>    at MS.Win32.UnsafeNativeMethods.DoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
>    at System.Windows.OleServicesContext.OleDoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
>    at System.Windows.DragDrop.OleDoDragDrop(DependencyObject dragSource, DataObject dataObject, DragDropEffects allowedEffects)
>    at System.Windows.DragDrop.DoDragDrop(DependencyObject dragSource, Object data, DragDropEffects allowedEffects)
>    at SEToolbox.Services.ListBoxItemDragBehavior.AssociatedObject_MouseLeave(Object sender, MouseEventArgs e) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\ListBoxItemDragBehavior.cs:line 154
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
>    at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
>    at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
>    at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
>    at System.Windows.ReverseInheritProperty.FirePropertyChangeInAncestry(DependencyObject element, Boolean oldValue, DeferredElementTreeState treeState, Action`2 originChangedAction)
>    at System.Windows.ReverseInheritProperty.OnOriginValueChanged(DependencyObject oldOrigin, DependencyObject newOrigin, IList`1 otherOrigins, DeferredElementTreeState& oldTreeState, Action`2 originChangedAction)
>    at System.Windows.Input.MouseDevice.ChangeMouseOver(IInputElement mouseOver, Int32 timestamp)
>    at System.Windows.Input.MouseDevice.PreNotifyInput(Object sender, NotifyInputEventArgs e)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 

**Additionally, the program also will crash with the same message, "Field not found: 'Sandbox.Common.ObjectBuilders.MyObjectBuilder_PistonBase.TopBlockId'" if I try to import the objects after exporting them.**

This is the general information provided by Event Viewer for import crash.

> 
> 2016-09-25 15:28:57,149 [1] FATAL SEToolbox.Support.DiagnosticsLogging [(null)] - Unhandled Exception
> Application: C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe
> CommandLine: "C:\Program Files (x86)\MidSpace\SEToolbox\SEToolbox.exe" 
> CurrentDirectory: C:\Program Files (x86)\MidSpace\SEToolbox
> SEBinPath: D:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64
> SEBinVersion: 1.149.4
> ProcessorCount: 8
> OSVersion: Microsoft Windows NT 6.2.9200.0
> Version: 4.0.30319.42000
> Is64BitOperatingSystem: True
> IntPtr.Size: 8
> IsAdmin: False
> CurrentUICulture: 
> CurrentCulture: 
> 
> Files:
> 2016-09-19T12:57:41.3795004-07:00	24,787,384		HavokWrapper.dll
> 2016-01-11T16:42:58.0000000-08:00	498,176	2014.2.17.1	HelixToolkit.Wpf.dll
> 2016-01-11T16:42:58.0000000-08:00	200,704	0.86.0.518	ICSharpCode.SharpZipLib.dll
> 2016-01-11T16:42:58.0000000-08:00	301,056	1.2.13.0	log4net.dll
> 2016-06-27T14:00:26.6301630-07:00	660,128	12.00.21005.1 built by: REL	msvcp120.dll
> 2016-06-27T14:00:27.6885533-07:00	963,232	12.00.21005.1 built by: REL	msvcr120.dll
> 2016-09-19T12:57:41.3779978-07:00	52,664	1.0.0.0	Sandbox.Common.dll
> 2016-09-19T12:57:43.7140684-07:00	5,791,672	1.0.0.0	Sandbox.Game.dll
> 2016-09-19T12:57:43.7140684-07:00	312,248	1.0.0.0	Sandbox.Graphics.dll
> 2016-08-27T10:49:42.0000000-07:00	1,204,224	01.144.000.0	SEToolbox.exe
> 2016-06-15T18:45:08.0000000-07:00	745		SEToolbox.exe.config
> 2016-08-24T22:12:40.0000000-07:00	27,136	1.0.0.0	SEToolbox.ImageLibrary.dll
> 2016-08-27T10:49:40.0000000-07:00	7,680	1.0.0.0	SEToolbox.ImageShaders.dll
> 2016-08-27T10:49:42.0000000-07:00	2,043,392		SEToolbox.pdb
> 2016-08-27T10:47:26.0000000-07:00	51,200	1.0.0.0	SEToolboxUpdate.exe
> 2016-09-19T12:57:41.3779978-07:00	262,072	3.0.1	SharpDX.dll
> 2016-09-19T12:57:44.5600622-07:00	328,632	1.0.0.0	SpaceEngineers.Game.dll
> 2016-09-19T12:57:44.4711451-07:00	51,128	1.0.0.0	SpaceEngineers.ObjectBuilders.dll
> 2016-09-19T12:57:41.3789998-07:00	10,587,576	1.0.0.0	SpaceEngineers.ObjectBuilders.XmlSerializers.dll
> 2016-09-19T12:57:44.4711451-07:00	537,016		SteamSDK.dll
> 2016-06-27T14:01:24.7466218-07:00	105,152	02.19.34.93	steam_api.dll
> 2016-06-27T14:00:27.3910490-07:00	119,488	02.19.34.93	steam_api64.dll
> 2016-01-11T16:42:58.0000000-08:00	39,936	2.0.20525.0	System.Windows.Interactivity.dll
> 2016-09-19T12:57:42.1952845-07:00	654,264	1.0.0.0	VRage.dll
> 2016-09-19T12:57:42.1952845-07:00	728,504	1.0.0.0	VRage.Game.dll
> 2016-09-19T12:57:44.5600622-07:00	2,766,264	1.0.0.0	VRage.Game.XmlSerializers.dll
> 2016-09-19T12:57:44.5595643-07:00	94,136	1.0.0.0	VRage.Input.dll
> 2016-09-19T12:57:42.6830532-07:00	648,632	1.0.0.0	VRage.Library.dll
> 2016-09-19T12:57:41.3795004-07:00	506,808	1.0.0.0	VRage.Math.dll
> 2016-09-19T12:57:42.1947607-07:00	76,728		VRage.Native.dll
> 2016-09-19T12:57:41.3789998-07:00	103,352	1.0.0.0	VRage.OpenVRWrapper.dll
> 2016-09-19T12:57:44.5610867-07:00	523,192	1.0.0.0	VRage.Render.dll
> 2016-09-19T12:57:42.6830532-07:00	604,600	1.0.0.0	VRage.Render11.dll
> 2016-01-11T16:42:58.0000000-08:00	64,512	2.2.0	WPFLocalizeExtension.dll
> 2016-01-11T16:42:58.0000000-08:00	26,624	1.1.6.3	XAMLMarkupExtensions.dll
> 
> System.MissingFieldException: Field not found: 'Sandbox.Common.ObjectBuilders.MyObjectBuilder_PistonBase.TopBlockId'.
>    at SEToolbox.Models.ExplorerModel.MergeData(MyObjectBuilder_CubeGrid cubeGridObject, Dictionary`2& idReplacementTable)
>    at SEToolbox.Models.ExplorerModel.LoadEntities(String[] filenames) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Models\ExplorerModel.cs:line 543
>    at SEToolbox.ViewModels.ExplorerViewModel.ImportSandboxObjectFromFile() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\ViewModels\ExplorerViewModel.cs:line 1473
>    at SEToolbox.ViewModels.ExplorerViewModel.ImportSandboxObjectExecuted() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\ViewModels\ExplorerViewModel.cs:line 757
>    at SEToolbox.Services.DelegateCommand.Execute() in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 72
>    at SEToolbox.Services.DelegateCommand.System.Windows.Input.ICommand.Execute(Object parameter) in D:\Development\GitHub\SEToolbox\Main\SEToolbox\SEToolbox\Services\DelegateCommand.cs:line 154
>    at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
>    at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>

**Comment by midspace** [comment]
It looks like Keen changed the underlying data structures for Pistons.
A new build of SEToolbox has fixed it.
Please download it from here: https://github.com/midspace/SEToolbox/releases/latest
