### ISSUE TITLE
Registry check failure for dedicated servers

### ISSUE THREAD

**Issue by scorpnoire** [midspace/SEToolbox#82]
Our dedicated server is installed without a full steam installation on some remote server machine.
Path to application:
C:\Steam\server\se\DedicatedServer64\SpaceEngineersDedicated.exe
The steam directory only contains the \scripts and \steamcmd subdirs.

Server updates are done via steamcmd.exe, called via .bat:

`@echo off
 
 SET STEAMLOGIN=anonymous anonymous
 SET BRANCH=298740
 SET SESRVPATH=C:\Steam\Server\se
 SET STEAMPATH=C:\Steam\steamcmd

:: _________________________________________________________

%STEAMPATH%\steamcmd.exe +login %STEAMLOGIN% +force_install_dir %SESRVPATH% +"app_update %BRANCH%" update +quit
%STEAMPATH%\steamcmd.exe +login %STEAMLOGIN% +force_install_dir %SESRVPATH% +"app_update %BRANCH%" validate +quit
pause`

So your registry check never finds any valid installation path and trying to add the keys manually fails due to missing folder structure for steam apps etc.

Is there a possibility to get the toolbox up and running without the registry check for dedicated servers?

**Comment by midspace** [comment]
It's a missing file in the Stable version of the Dedicated server.
See the following for a workaround.
https://github.com/midspace/SEToolbox/issues/78
