### ISSUE TITLE
Mirroring of certain blocks doesn't work

### ISSUE THREAD

**Issue by Brommbeere** [midspace/SEToolbox#86]
Light Armor Corner 2 * 1 * 1 base +tip and the Light Round Corner won't mirror correctly when using the mirroring tool, they are completely messed up on use. I guess the issue will be the same for the heavy armor blocks of the same type. All other blocks seem to be mirroring correctly.

Edit: I tried all 3 mirroring Options,  issue still there; I'm using the stable Version 1.157 and took the newest SEToolbox-01.153.010.1

**Comment by midspace** [comment]
Duplicate of #10
