### ISSUE TITLE
Not Compatible with win 10

### ISSUE THREAD

**Issue by marcmarder161** [midspace/SEToolbox#88]
SEToolboxSetup\SEToolboxSetup.wixproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkId=659044&projecttype=930C7802-8A8C-48F9-8165-68863BCCD9DD

The Link provided is from 2010 and is not working with win 10

**Comment by midspace** [comment]
It sounds like you are trying to open the SEToolbox solution.

Please make sure you have read the developer notes, and that you have installed the build requirements.
https://github.com/midspace/SEToolbox/wiki/Working-with-and-developing-SEToolbox

The link you have provided, specifically points to the Windows Installer XML (WiX) toolset, which is listed in the SEToolbox developer notes.

**Comment by midspace** [comment]
There has been no response to this issue from the reporter for over a month.
