### ISSUE TITLE
"Invalid Location Sepcified" when running SEToolbox  on DS, Stable 1.172

### ISSUE THREAD

**Issue by scorpnoire** [midspace/SEToolbox#89]
Edit:  reg. Dedicated Server from the Public 1.172 branch of SE

Same error like in issues #81 though the old workaround with the VRage.Render11.dll is NOT working.

Any advice?

**Comment by midspace** [comment]
If you are running the Dedicated Server from the Public 1.172 branch of SE,

Copy the `System.Data.SQLite.dll` file from the game's `Bin64` to your deployed Dedicated server path.
This should allow SEToolbox to work.

**Comment by scorpnoire** [comment]
Thank you for your quick reply.

Workaround confirmed working. :)

**Comment by midspace** [comment]
The missing file should be part of the SE Dedicated server now.
This shouldn't be an issue any longer.
