### ISSUE TITLE
Asteroid materials not being displayed for save game from SE 01_172_020

### ISSUE THREAD

**Issue by DelboyJay** [midspace/SEToolbox#92]
I'm running Space Engineers SE 01_172_020 64Bit and I wanted to have a look at my save game to check for Cobalt because I cannot find any in-game. I've run SEToolbox-01.168.006.1 and loaded my save game but none of the asteroids seem to have any materials. Obviously in-game every asteroid has at least iron and usually ice but the materials list in SE Toolkit is completely empty for all asteroids listed.

Am I doing something wrong here or have they changed the save game format and SE Toolkit needs an update?

**Comment by DelboyJay** [comment]
I've added my save game in case it helps:

[Lone Survivor 2017-02-13 12-26.zip](https://github.com/midspace/SEToolbox/files/790474/Lone.Survivor.2017-02-13.12-26.zip)

**Comment by midspace** [comment]
Please see the following regarding asteroid issues.
https://github.com/midspace/SEToolbox/wiki/New-Asteroid-file-format

**Comment by midspace** [comment]
There has been no response to this issue from the reporter for over a month.
