### ISSUE TITLE
v01.179.001.1  Generat Asteroid Field

### ISSUE THREAD

**Issue by Azuna1** [midspace/SEToolbox#94]
Nvm just found 
https://github.com/midspace/SEToolbox/wiki/New-Asteroid-file-format

the supplied link is dead though.. Any way to still create asteroids?
https://dl.dropboxusercontent.com/u/26211652/SE-VoxelMaps-v59.zip

**Comment by midspace** [comment]
I've updated the link in the wiki.
Please tell me if there are any problems with the new link.

**Comment by Azuna1** [comment]
link works fine, now its time to figure out how to use em :)
