### ISSUE TITLE
SEToolbox.exe just disappears

### ISSUE THREAD

**Issue by Klistofklades** [midspace/SEToolbox#95]
I installed it with the .msi, and the .exe just...vanishes...the shortcut doesn't work, because the .exe is missing.

So....I uninstalled it with the .msi and simply extracted it from the .zip. I see it appear, yay, then a second later poof, it disappears. No clue what is going on.

Using Windows 10.

**Comment by midspace** [comment]
Did you work it out since you have closed this issue?
