### ISSUE TITLE
SEToolbox 1.179.1.1 Loops base file update

### ISSUE THREAD

**Issue by darth-crunchus** [midspace/SEToolbox#96]
As the title suggests, on Windows 10 (1703) after having updated to 1.179.1.1, SEToolbox asks to update the Space Engineers base files for itself, as is the norm for an update.  Upon clicking 'OK' on the subsequent UAC prompt, SEToolbox proceeds to prompt the user to allow it to update the base files.  This goes on continuously, and if the user elects to deny the UAC request, after confirming that the user is fine with accepting the risks of continuing with old base files, SEToolbox reports that it has found Space Engineers version '0.0" in 'D:\Program Files (x86)\Steam\SteamApps\Common\SpaceEngineers\Bin64', and points out that the user should update it before running SEToolbox 1.179.1.1 again.  I don't know if this is a snafu on KEEN's part or not, but I thought I'd bring it to attention.  Oh, and I should also add that my Space Engineers version is 1.180.1.

**Comment by midspace** [comment]
Sounds kinda of weird.
Have you by any chance switch between versions of Space Engineers recently using the "Betas" tab in Steam?

I can only recommend re-running the .msi installer, and clicking "Repair".
The next time you run SEToolbox then, it should be able to cleanly update the files it needs from your current Space Engineers.

The current Space Engineers should be up to 1.180.106

**Comment by darth-crunchus** [comment]
Yeah, repairing it did the trick.  I can't believe I didn't think to do
that.   I apologize for the brain fart.
