### ISSUE TITLE
Copy Text To Clipboard output format changed

### ISSUE THREAD

**Issue by Flatfoot** [midspace/SEToolbox#97]
The format of the copy text output is no longer the same as previous versions (it broke excel tools that I use).  This can be identified by pasting any ship data into an excel file.   The columns don't line up like they should.

**Comment by midspace** [comment]
Can you provide a copy of the world that is doing this?
It sounds like a particular mod may be causing an issue.

**Comment by Flatfoot** [comment]
Go figure.. a power cycle fixes everything.  seemed to be a fluke after the patch.  Resolved by powercycling the computer.
