### ISSUE TITLE
Character Inventory changes do not save

### ISSUE THREAD

**Issue by Anora** [midspace/SEToolbox#98]
So there was a recent update when I did a minor change and saved then loaded the save in game the change has not taken place this change was adding things to player inventory

**Comment by midspace** [comment]
The Character information has changed when a player is in a cockpit, passenger seat, or cryo chamber.
So this bug only occurs then.
It does not affect a player character when they are outside or free floating.

**Comment by midspace** [comment]
This has been added in the new release.
https://github.com/midspace/SEToolbox/releases/latest

Please test it and advise me if it isn't working.
